[book]
authors = ["Rudolf Kreibich"]
language = "cz"
multilingual = false
src = "src"
title = "Poznámky ke hře kterou nikdy nevytvořím."
descriptiom = "Civilizace a hry na ně"

[build]
build-dir = "../docs"